package com.pixel.intelligentsearch.core.theme

import androidx.compose.ui.graphics.Color

val GoogleDarkPrimary = Color(0xFFA8C7FA)
val GoogleDarkOnPrimary = Color(0xFF062E6F)
val GoogleDarkPrimaryContainer = Color(0xFF0842A0)
val GoogleDarkOnPrimaryContainer = Color(0xFFD3E3FD)
val GoogleDarkSecondary = Color(0xFF7FCFFF)
val GoogleDarkOnSecondary = Color(0xFF00344F)
val GoogleDarkSecondaryContainer = Color(0xFF004A77)
val GoogleDarkOnSecondaryContainer = Color(0xFFC2E7FF)
val GoogleDarkTertiary = Color(0xFF6DD5ED)
val GoogleDarkOnTertiary = Color(0xFF00363F)
val GoogleDarkTertiaryContainer = Color(0xFF004E5B)
val GoogleDarkOnTertiaryContainer = Color(0xFFA8EFFF)
val GoogleDarkSurface = Color(0xFF131314)
val GoogleDarkOnSurface = Color(0xFFE3E3E3)
val GoogleDarkOnSurfaceVariant = Color(0xFFC4C7C5)
val GoogleDarkSurfaceContainer = Color(0xFF1E1F20)
val GoogleDarkSurfaceContainerLow = Color(0xFF171718)
val GoogleDarkSurfaceContainerHigh = Color(0xFF28292A)
val GoogleDarkSurfaceContainerHighest = Color(0xFF333537)
val GoogleDarkOutline = Color(0xFF8E918F)
val GoogleDarkOutlineVariant = Color(0xFF444746)

val GoogleLightPrimary = Color(0xFF0B57D0)
val GoogleLightOnPrimary = Color(0xFFFFFFFF)
val GoogleLightPrimaryContainer = Color(0xFFD3E3FD)
val GoogleLightOnPrimaryContainer = Color(0xFF041E49)
val GoogleLightSecondary = Color(0xFF00639B)
val GoogleLightOnSecondary = Color(0xFFFFFFFF)
val GoogleLightSecondaryContainer = Color(0xFFC2E7FF)
val GoogleLightOnSecondaryContainer = Color(0xFF001D35)
val GoogleLightTertiary = Color(0xFF006879)
val GoogleLightOnTertiary = Color(0xFFFFFFFF)
val GoogleLightTertiaryContainer = Color(0xFFA8EFFF)
val GoogleLightOnTertiaryContainer = Color(0xFF001F25)
val GoogleLightSurface = Color(0xFFFFFFFF)
val GoogleLightOnSurface = Color(0xFF1F1F1F)
val GoogleLightOnSurfaceVariant = Color(0xFF444746)
val GoogleLightSurfaceContainer = Color(0xFFF0F4F9)
val GoogleLightSurfaceContainerLow = Color(0xFFF7F9FC)
val GoogleLightSurfaceContainerHigh = Color(0xFFE9EEF6)
val GoogleLightSurfaceContainerHighest = Color(0xFFE1E6ED)
val GoogleLightOutline = Color(0xFF747775)
val GoogleLightOutlineVariant = Color(0xFFC4C7C5)
