package com.pixel.intelligentsearch.feature.widget.doodle

import android.content.Context
import android.content.Intent
import android.widget.RemoteViews
import android.widget.RemoteViewsService
import com.pixel.intelligentsearch.R

class DoodleWidgetService : RemoteViewsService() {
    override fun onGetViewFactory(intent: Intent): RemoteViewsFactory {
        return DoodleViewsFactory(this.applicationContext)
    }
}

class DoodleViewsFactory(private val context: Context) : RemoteViewsService.RemoteViewsFactory {
    
    private val allDoodles = listOf(
        intArrayOf(
            R.drawable.doodle_bastille_day_0,
            R.drawable.doodle_bastille_day_1,
            R.drawable.doodle_bastille_day_2,
            R.drawable.doodle_bastille_day_3,
            R.drawable.doodle_bastille_day_4,
            R.drawable.doodle_bastille_day_5,
            R.drawable.doodle_bastille_day_6,
            R.drawable.doodle_bastille_day_7,
            R.drawable.doodle_bastille_day_8,
            R.drawable.doodle_bastille_day_9,
            R.drawable.doodle_bastille_day_10,
            R.drawable.doodle_bastille_day_11,
            R.drawable.doodle_bastille_day_12,
            R.drawable.doodle_bastille_day_13
        ),
        intArrayOf(
            R.drawable.doodle_christmas_0,
            R.drawable.doodle_christmas_1,
            R.drawable.doodle_christmas_2,
            R.drawable.doodle_christmas_3,
            R.drawable.doodle_christmas_4,
            R.drawable.doodle_christmas_5,
            R.drawable.doodle_christmas_6,
            R.drawable.doodle_christmas_7,
            R.drawable.doodle_christmas_8,
            R.drawable.doodle_christmas_9,
            R.drawable.doodle_christmas_10,
            R.drawable.doodle_christmas_11,
            R.drawable.doodle_christmas_12,
            R.drawable.doodle_christmas_13
        ),
        intArrayOf(
            R.drawable.doodle_cinco_de_mayo_0,
            R.drawable.doodle_cinco_de_mayo_1,
            R.drawable.doodle_cinco_de_mayo_2,
            R.drawable.doodle_cinco_de_mayo_3,
            R.drawable.doodle_cinco_de_mayo_4,
            R.drawable.doodle_cinco_de_mayo_5,
            R.drawable.doodle_cinco_de_mayo_6,
            R.drawable.doodle_cinco_de_mayo_7,
            R.drawable.doodle_cinco_de_mayo_8,
            R.drawable.doodle_cinco_de_mayo_9,
            R.drawable.doodle_cinco_de_mayo_10,
            R.drawable.doodle_cinco_de_mayo_11,
            R.drawable.doodle_cinco_de_mayo_12,
            R.drawable.doodle_cinco_de_mayo_13
        ),
        intArrayOf(
            R.drawable.doodle_day_of_the_dead_0,
            R.drawable.doodle_day_of_the_dead_1,
            R.drawable.doodle_day_of_the_dead_2,
            R.drawable.doodle_day_of_the_dead_3,
            R.drawable.doodle_day_of_the_dead_4,
            R.drawable.doodle_day_of_the_dead_5,
            R.drawable.doodle_day_of_the_dead_6,
            R.drawable.doodle_day_of_the_dead_7,
            R.drawable.doodle_day_of_the_dead_8,
            R.drawable.doodle_day_of_the_dead_9,
            R.drawable.doodle_day_of_the_dead_10,
            R.drawable.doodle_day_of_the_dead_11,
            R.drawable.doodle_day_of_the_dead_12,
            R.drawable.doodle_day_of_the_dead_13
        ),
        intArrayOf(
            R.drawable.doodle_diwali_0,
            R.drawable.doodle_diwali_1,
            R.drawable.doodle_diwali_2,
            R.drawable.doodle_diwali_3,
            R.drawable.doodle_diwali_4,
            R.drawable.doodle_diwali_5,
            R.drawable.doodle_diwali_6,
            R.drawable.doodle_diwali_7,
            R.drawable.doodle_diwali_8,
            R.drawable.doodle_diwali_9,
            R.drawable.doodle_diwali_10,
            R.drawable.doodle_diwali_11,
            R.drawable.doodle_diwali_12,
            R.drawable.doodle_diwali_13
        ),
        intArrayOf(
            R.drawable.doodle_earth_day_0,
            R.drawable.doodle_earth_day_1,
            R.drawable.doodle_earth_day_2,
            R.drawable.doodle_earth_day_3,
            R.drawable.doodle_earth_day_4,
            R.drawable.doodle_earth_day_5,
            R.drawable.doodle_earth_day_6,
            R.drawable.doodle_earth_day_7,
            R.drawable.doodle_earth_day_8,
            R.drawable.doodle_earth_day_9,
            R.drawable.doodle_earth_day_10,
            R.drawable.doodle_earth_day_11,
            R.drawable.doodle_earth_day_12,
            R.drawable.doodle_earth_day_13
        ),
        intArrayOf(
            R.drawable.doodle_easter_0,
            R.drawable.doodle_easter_1,
            R.drawable.doodle_easter_2,
            R.drawable.doodle_easter_3,
            R.drawable.doodle_easter_4,
            R.drawable.doodle_easter_5,
            R.drawable.doodle_easter_6,
            R.drawable.doodle_easter_7,
            R.drawable.doodle_easter_8,
            R.drawable.doodle_easter_9,
            R.drawable.doodle_easter_10,
            R.drawable.doodle_easter_11,
            R.drawable.doodle_easter_12,
            R.drawable.doodle_easter_13
        ),
        intArrayOf(
            R.drawable.doodle_fathers_day_0,
            R.drawable.doodle_fathers_day_1,
            R.drawable.doodle_fathers_day_2,
            R.drawable.doodle_fathers_day_3,
            R.drawable.doodle_fathers_day_4,
            R.drawable.doodle_fathers_day_5,
            R.drawable.doodle_fathers_day_6,
            R.drawable.doodle_fathers_day_7,
            R.drawable.doodle_fathers_day_8,
            R.drawable.doodle_fathers_day_9,
            R.drawable.doodle_fathers_day_10,
            R.drawable.doodle_fathers_day_11,
            R.drawable.doodle_fathers_day_12,
            R.drawable.doodle_fathers_day_13
        ),
        intArrayOf(
            R.drawable.doodle_halloween_0,
            R.drawable.doodle_halloween_1,
            R.drawable.doodle_halloween_2,
            R.drawable.doodle_halloween_3,
            R.drawable.doodle_halloween_4,
            R.drawable.doodle_halloween_5,
            R.drawable.doodle_halloween_6,
            R.drawable.doodle_halloween_7,
            R.drawable.doodle_halloween_8,
            R.drawable.doodle_halloween_9,
            R.drawable.doodle_halloween_10,
            R.drawable.doodle_halloween_11,
            R.drawable.doodle_halloween_12,
            R.drawable.doodle_halloween_13
        ),
        intArrayOf(
            R.drawable.doodle_hanukkah_0,
            R.drawable.doodle_hanukkah_1,
            R.drawable.doodle_hanukkah_2,
            R.drawable.doodle_hanukkah_3,
            R.drawable.doodle_hanukkah_4,
            R.drawable.doodle_hanukkah_5,
            R.drawable.doodle_hanukkah_6,
            R.drawable.doodle_hanukkah_7,
            R.drawable.doodle_hanukkah_8,
            R.drawable.doodle_hanukkah_9,
            R.drawable.doodle_hanukkah_10,
            R.drawable.doodle_hanukkah_11,
            R.drawable.doodle_hanukkah_12,
            R.drawable.doodle_hanukkah_13
        ),
        intArrayOf(
            R.drawable.doodle_independence_day_0,
            R.drawable.doodle_independence_day_1,
            R.drawable.doodle_independence_day_2,
            R.drawable.doodle_independence_day_3,
            R.drawable.doodle_independence_day_4,
            R.drawable.doodle_independence_day_5,
            R.drawable.doodle_independence_day_6,
            R.drawable.doodle_independence_day_7,
            R.drawable.doodle_independence_day_8,
            R.drawable.doodle_independence_day_9,
            R.drawable.doodle_independence_day_10,
            R.drawable.doodle_independence_day_11,
            R.drawable.doodle_independence_day_12,
            R.drawable.doodle_independence_day_13
        ),
        intArrayOf(
            R.drawable.doodle_indigenous_peoples_day_0,
            R.drawable.doodle_indigenous_peoples_day_1,
            R.drawable.doodle_indigenous_peoples_day_2,
            R.drawable.doodle_indigenous_peoples_day_3,
            R.drawable.doodle_indigenous_peoples_day_4,
            R.drawable.doodle_indigenous_peoples_day_5,
            R.drawable.doodle_indigenous_peoples_day_6,
            R.drawable.doodle_indigenous_peoples_day_7,
            R.drawable.doodle_indigenous_peoples_day_8,
            R.drawable.doodle_indigenous_peoples_day_9,
            R.drawable.doodle_indigenous_peoples_day_10,
            R.drawable.doodle_indigenous_peoples_day_11,
            R.drawable.doodle_indigenous_peoples_day_12,
            R.drawable.doodle_indigenous_peoples_day_13
        ),
        intArrayOf(
            R.drawable.doodle_juneteenth_0,
            R.drawable.doodle_juneteenth_1,
            R.drawable.doodle_juneteenth_2,
            R.drawable.doodle_juneteenth_3,
            R.drawable.doodle_juneteenth_4,
            R.drawable.doodle_juneteenth_5,
            R.drawable.doodle_juneteenth_6,
            R.drawable.doodle_juneteenth_7,
            R.drawable.doodle_juneteenth_8,
            R.drawable.doodle_juneteenth_9,
            R.drawable.doodle_juneteenth_10,
            R.drawable.doodle_juneteenth_11,
            R.drawable.doodle_juneteenth_12,
            R.drawable.doodle_juneteenth_13
        ),
        intArrayOf(
            R.drawable.doodle_kwanzaa_0,
            R.drawable.doodle_kwanzaa_1,
            R.drawable.doodle_kwanzaa_2,
            R.drawable.doodle_kwanzaa_3,
            R.drawable.doodle_kwanzaa_4,
            R.drawable.doodle_kwanzaa_5,
            R.drawable.doodle_kwanzaa_6,
            R.drawable.doodle_kwanzaa_7,
            R.drawable.doodle_kwanzaa_8,
            R.drawable.doodle_kwanzaa_9,
            R.drawable.doodle_kwanzaa_10,
            R.drawable.doodle_kwanzaa_11,
            R.drawable.doodle_kwanzaa_12,
            R.drawable.doodle_kwanzaa_13
        ),
        intArrayOf(
            R.drawable.doodle_labor_day_0,
            R.drawable.doodle_labor_day_1,
            R.drawable.doodle_labor_day_2,
            R.drawable.doodle_labor_day_3,
            R.drawable.doodle_labor_day_4,
            R.drawable.doodle_labor_day_5,
            R.drawable.doodle_labor_day_6,
            R.drawable.doodle_labor_day_7,
            R.drawable.doodle_labor_day_8,
            R.drawable.doodle_labor_day_9,
            R.drawable.doodle_labor_day_10,
            R.drawable.doodle_labor_day_11,
            R.drawable.doodle_labor_day_12,
            R.drawable.doodle_labor_day_13
        ),
        intArrayOf(
            R.drawable.doodle_lunar_new_year_0,
            R.drawable.doodle_lunar_new_year_1,
            R.drawable.doodle_lunar_new_year_2,
            R.drawable.doodle_lunar_new_year_3,
            R.drawable.doodle_lunar_new_year_4,
            R.drawable.doodle_lunar_new_year_5,
            R.drawable.doodle_lunar_new_year_6,
            R.drawable.doodle_lunar_new_year_7,
            R.drawable.doodle_lunar_new_year_8,
            R.drawable.doodle_lunar_new_year_9,
            R.drawable.doodle_lunar_new_year_10,
            R.drawable.doodle_lunar_new_year_11,
            R.drawable.doodle_lunar_new_year_12,
            R.drawable.doodle_lunar_new_year_13
        ),
        intArrayOf(
            R.drawable.doodle_memorial_day_0,
            R.drawable.doodle_memorial_day_1,
            R.drawable.doodle_memorial_day_2,
            R.drawable.doodle_memorial_day_3,
            R.drawable.doodle_memorial_day_4,
            R.drawable.doodle_memorial_day_5,
            R.drawable.doodle_memorial_day_6,
            R.drawable.doodle_memorial_day_7,
            R.drawable.doodle_memorial_day_8,
            R.drawable.doodle_memorial_day_9,
            R.drawable.doodle_memorial_day_10,
            R.drawable.doodle_memorial_day_11,
            R.drawable.doodle_memorial_day_12,
            R.drawable.doodle_memorial_day_13
        ),
        intArrayOf(
            R.drawable.doodle_mlk_day_0,
            R.drawable.doodle_mlk_day_1,
            R.drawable.doodle_mlk_day_2,
            R.drawable.doodle_mlk_day_3,
            R.drawable.doodle_mlk_day_4,
            R.drawable.doodle_mlk_day_5,
            R.drawable.doodle_mlk_day_6,
            R.drawable.doodle_mlk_day_7,
            R.drawable.doodle_mlk_day_8,
            R.drawable.doodle_mlk_day_9,
            R.drawable.doodle_mlk_day_10,
            R.drawable.doodle_mlk_day_11,
            R.drawable.doodle_mlk_day_12,
            R.drawable.doodle_mlk_day_13
        ),
        intArrayOf(
            R.drawable.doodle_mothers_day_0,
            R.drawable.doodle_mothers_day_1,
            R.drawable.doodle_mothers_day_2,
            R.drawable.doodle_mothers_day_3,
            R.drawable.doodle_mothers_day_4,
            R.drawable.doodle_mothers_day_5,
            R.drawable.doodle_mothers_day_6,
            R.drawable.doodle_mothers_day_7,
            R.drawable.doodle_mothers_day_8,
            R.drawable.doodle_mothers_day_9,
            R.drawable.doodle_mothers_day_10,
            R.drawable.doodle_mothers_day_11,
            R.drawable.doodle_mothers_day_12,
            R.drawable.doodle_mothers_day_13
        ),
        intArrayOf(
            R.drawable.doodle_new_years_day_0,
            R.drawable.doodle_new_years_day_1,
            R.drawable.doodle_new_years_day_2,
            R.drawable.doodle_new_years_day_3,
            R.drawable.doodle_new_years_day_4,
            R.drawable.doodle_new_years_day_5,
            R.drawable.doodle_new_years_day_6,
            R.drawable.doodle_new_years_day_7,
            R.drawable.doodle_new_years_day_8,
            R.drawable.doodle_new_years_day_9,
            R.drawable.doodle_new_years_day_10,
            R.drawable.doodle_new_years_day_11,
            R.drawable.doodle_new_years_day_12,
            R.drawable.doodle_new_years_day_13
        ),
        intArrayOf(
            R.drawable.doodle_new_years_eve_0,
            R.drawable.doodle_new_years_eve_1,
            R.drawable.doodle_new_years_eve_2,
            R.drawable.doodle_new_years_eve_3,
            R.drawable.doodle_new_years_eve_4,
            R.drawable.doodle_new_years_eve_5,
            R.drawable.doodle_new_years_eve_6,
            R.drawable.doodle_new_years_eve_7,
            R.drawable.doodle_new_years_eve_8,
            R.drawable.doodle_new_years_eve_9,
            R.drawable.doodle_new_years_eve_10,
            R.drawable.doodle_new_years_eve_11,
            R.drawable.doodle_new_years_eve_12,
            R.drawable.doodle_new_years_eve_13
        ),
        intArrayOf(
            R.drawable.doodle_oktoberfest_0,
            R.drawable.doodle_oktoberfest_1,
            R.drawable.doodle_oktoberfest_2,
            R.drawable.doodle_oktoberfest_3,
            R.drawable.doodle_oktoberfest_4,
            R.drawable.doodle_oktoberfest_5,
            R.drawable.doodle_oktoberfest_6,
            R.drawable.doodle_oktoberfest_7,
            R.drawable.doodle_oktoberfest_8,
            R.drawable.doodle_oktoberfest_9,
            R.drawable.doodle_oktoberfest_10,
            R.drawable.doodle_oktoberfest_11,
            R.drawable.doodle_oktoberfest_12,
            R.drawable.doodle_oktoberfest_13
        ),
        intArrayOf(
            R.drawable.doodle_patriot_day_0,
            R.drawable.doodle_patriot_day_1,
            R.drawable.doodle_patriot_day_2,
            R.drawable.doodle_patriot_day_3,
            R.drawable.doodle_patriot_day_4,
            R.drawable.doodle_patriot_day_5,
            R.drawable.doodle_patriot_day_6,
            R.drawable.doodle_patriot_day_7,
            R.drawable.doodle_patriot_day_8,
            R.drawable.doodle_patriot_day_9,
            R.drawable.doodle_patriot_day_10,
            R.drawable.doodle_patriot_day_11,
            R.drawable.doodle_patriot_day_12,
            R.drawable.doodle_patriot_day_13
        ),
        intArrayOf(
            R.drawable.doodle_presidents_day_0,
            R.drawable.doodle_presidents_day_1,
            R.drawable.doodle_presidents_day_2,
            R.drawable.doodle_presidents_day_3,
            R.drawable.doodle_presidents_day_4,
            R.drawable.doodle_presidents_day_5,
            R.drawable.doodle_presidents_day_6,
            R.drawable.doodle_presidents_day_7,
            R.drawable.doodle_presidents_day_8,
            R.drawable.doodle_presidents_day_9,
            R.drawable.doodle_presidents_day_10,
            R.drawable.doodle_presidents_day_11,
            R.drawable.doodle_presidents_day_12,
            R.drawable.doodle_presidents_day_13
        ),
        intArrayOf(
            R.drawable.doodle_pride_month_0,
            R.drawable.doodle_pride_month_1,
            R.drawable.doodle_pride_month_2,
            R.drawable.doodle_pride_month_3,
            R.drawable.doodle_pride_month_4,
            R.drawable.doodle_pride_month_5,
            R.drawable.doodle_pride_month_6,
            R.drawable.doodle_pride_month_7,
            R.drawable.doodle_pride_month_8,
            R.drawable.doodle_pride_month_9,
            R.drawable.doodle_pride_month_10,
            R.drawable.doodle_pride_month_11,
            R.drawable.doodle_pride_month_12,
            R.drawable.doodle_pride_month_13
        ),
        intArrayOf(
            R.drawable.doodle_st_patricks_day_0,
            R.drawable.doodle_st_patricks_day_1,
            R.drawable.doodle_st_patricks_day_2,
            R.drawable.doodle_st_patricks_day_3,
            R.drawable.doodle_st_patricks_day_4,
            R.drawable.doodle_st_patricks_day_5,
            R.drawable.doodle_st_patricks_day_6,
            R.drawable.doodle_st_patricks_day_7,
            R.drawable.doodle_st_patricks_day_8,
            R.drawable.doodle_st_patricks_day_9,
            R.drawable.doodle_st_patricks_day_10,
            R.drawable.doodle_st_patricks_day_11,
            R.drawable.doodle_st_patricks_day_12,
            R.drawable.doodle_st_patricks_day_13
        ),
        intArrayOf(
            R.drawable.doodle_thanksgiving_0,
            R.drawable.doodle_thanksgiving_1,
            R.drawable.doodle_thanksgiving_2,
            R.drawable.doodle_thanksgiving_3,
            R.drawable.doodle_thanksgiving_4,
            R.drawable.doodle_thanksgiving_5,
            R.drawable.doodle_thanksgiving_6,
            R.drawable.doodle_thanksgiving_7,
            R.drawable.doodle_thanksgiving_8,
            R.drawable.doodle_thanksgiving_9,
            R.drawable.doodle_thanksgiving_10,
            R.drawable.doodle_thanksgiving_11,
            R.drawable.doodle_thanksgiving_12,
            R.drawable.doodle_thanksgiving_13
        ),
        intArrayOf(
            R.drawable.doodle_valentines_day_0,
            R.drawable.doodle_valentines_day_1,
            R.drawable.doodle_valentines_day_2,
            R.drawable.doodle_valentines_day_3,
            R.drawable.doodle_valentines_day_4,
            R.drawable.doodle_valentines_day_5,
            R.drawable.doodle_valentines_day_6,
            R.drawable.doodle_valentines_day_7,
            R.drawable.doodle_valentines_day_8,
            R.drawable.doodle_valentines_day_9,
            R.drawable.doodle_valentines_day_10,
            R.drawable.doodle_valentines_day_11,
            R.drawable.doodle_valentines_day_12,
            R.drawable.doodle_valentines_day_13
        ),
        intArrayOf(
            R.drawable.doodle_veterans_day_0,
            R.drawable.doodle_veterans_day_1,
            R.drawable.doodle_veterans_day_2,
            R.drawable.doodle_veterans_day_3,
            R.drawable.doodle_veterans_day_4,
            R.drawable.doodle_veterans_day_5,
            R.drawable.doodle_veterans_day_6,
            R.drawable.doodle_veterans_day_7,
            R.drawable.doodle_veterans_day_8,
            R.drawable.doodle_veterans_day_9,
            R.drawable.doodle_veterans_day_10,
            R.drawable.doodle_veterans_day_11,
            R.drawable.doodle_veterans_day_12,
            R.drawable.doodle_veterans_day_13
        ),
        intArrayOf(
            R.drawable.doodle_womens_day_0,
            R.drawable.doodle_womens_day_1,
            R.drawable.doodle_womens_day_2,
            R.drawable.doodle_womens_day_3,
            R.drawable.doodle_womens_day_4,
            R.drawable.doodle_womens_day_5,
            R.drawable.doodle_womens_day_6,
            R.drawable.doodle_womens_day_7,
            R.drawable.doodle_womens_day_8,
            R.drawable.doodle_womens_day_9,
            R.drawable.doodle_womens_day_10,
            R.drawable.doodle_womens_day_11,
            R.drawable.doodle_womens_day_12,
            R.drawable.doodle_womens_day_13
        )
    )
    
    private var currentFrames: IntArray = intArrayOf()

    override fun onCreate() {
        currentFrames = allDoodles.random()
    }

    override fun onDataSetChanged() {
        currentFrames = allDoodles.random()
    }

    override fun onDestroy() {}

    override fun getCount(): Int = currentFrames.size

    override fun getViewAt(position: Int): RemoteViews {
        val views = RemoteViews(context.packageName, R.layout.widget_doodle_frame)
        views.setImageViewResource(R.id.doodle_frame_image, currentFrames[position])
        return views
    }

    override fun getLoadingView(): RemoteViews? = null
    override fun getViewTypeCount(): Int = 1
    override fun getItemId(position: Int): Long = position.toLong()
    override fun hasStableIds(): Boolean = true
}



